config/database.yml, config/puma.rb
See
https://devcenter.heroku.com/articles/concurrency-and-database-connections
=> Configure database connections to be the same as Puma threads

.travis.yml
This reverts commit 7e550e688e7cabf3bd6ca141413cc7f228dc3a99, reversing
changes made to 2eeb6628f308024631b551ba63506b13f0bff018.
=> Revert "Merge pull request #352 from obduk/travis_trusty"

app/controllers/application_controller.rb, spec/features/application/unknown_routes_spec.rb
This reverts commit 4e81594f4f582f88774be7a2533b536a60ea644f, reversing
changes made to 081d7927d50849f4af29626f76b6b2f943395250.
=> Revert "Merge pull request #402 from obduk/html_extensions"

Gemfile
This reverts commit bf9edb9d00d2a7a699c501016d027f3643ff1b8e, reversing
changes made to 97ac8735a4b81cc73f341e9cc10551407f6c8258.
=> Revert "Merge pull request #477 from obduk/fix_error"

.travis.yml, Gemfile, Gemfile.lock, app.json, config/initializers/session_store.rb, config/puma.rb, config/secrets.yml, puppet/manifests/default.pp, spec/features/users/login_spec.rb, spec/features/users/logout_spec.rb
=> Remove Redis

app/models/page.rb, app/views/pages/show.html.haml, config/brakeman.yml, db/migrate/20160609090557_add_custom_html_to_pages.rb, db/schema.rb, spec/factories/page_factory.rb, spec/features/pages/show_spec.rb, spec/models/page_spec.rb
=> Added custom html section to page

config/tinymce.yml
=> Clean up TinyMCE buttons

app/models/image.rb, app/models/message.rb, app/models/page.rb, app/models/site.rb, app/models/user.rb
=> Strip new lines from fields

app/models/page.rb, spec/models/page_spec.rb
=> Clean HTML

.env.test, config/application.rb, config/initializers/assets.rb, spec/features/application/secure_headers_spec.rb
=> Fix asset_host

.rubocop.yml, app/views/devise/invitations/edit.html.haml, app/views/devise/passwords/edit.html.haml, app/views/devise/registrations/edit.html.haml, app/views/layouts/_footer.html.haml, app/views/layouts/_topbar.html.haml, config/locales/models/default/en.yml, config/locales/models/user/en.yml, config/locales/views/devise/invitations/en.yml, config/locales/views/devise/passwords/en.yml, config/locales/views/layouts/en.yml
=> Added more text to locales

Gemfile
https://rollbar.com/obduk-cms-production/obduk-cms-production/items/155/
=> Attempt to fix bh error

bin/backup
Changed to inserts due to using older version of PostgreSQL, also
removed owners so can be restored to any database.
Resolves #548
=> Fix database backups

Berksfile, Berksfile.lock, Vagrantfile, chef/roles/development.json, chef/vagrant.rb
=> Added chef role for development

README.md
=> Added dependencyci.com

app.json
=> Added formation to Heroku app.json

bower.json, dependencyci.yml, vendor/assets/bower_components/autogrow-textarea/.bower.json, vendor/assets/bower_components/jquery/.bower.json
=> Fix bower.json syntax

.editorconfig
=> Added editorconfig.org file

config/initializers/rollbar.rb
=> Only enable rollbar if key is present

app/jobs/base_job.rb, app/jobs/clean_s3_job.rb, app/jobs/daily_job.rb, app/jobs/validate_data_job.rb, config/locales/jobs/clean_s3_job/en.yml, config/locales/jobs/validate_data_job/en.yml
=> Move job errors to translations

Gemfile, Gemfile.lock
=> Clean up Gemfile

doc/optional.md
=> Add more Cloud Watch alarms

doc/optional.md
=> Add AWS budget

config/initializers/bullet.rb, spec/factories/image_factory.rb, spec/factories/message_factory.rb, spec/factories/page_factory.rb, spec/factories/site_setting_factory.rb, spec/features/images/index_spec.rb, spec/features/messages/index_spec.rb, spec/features/messages/show_spec.rb, spec/features/pages/contact_form_spec.rb, spec/features/pages/index_spec.rb, spec/features/pages/show_spec.rb, spec/support/features/test_site.rb
Simplify fixtures to use standard relations method.
Resolves #633
=> Simplify fixtures

app/jobs/application_job.rb, app/jobs/clean_s3_job.rb, app/jobs/daily_job.rb, app/jobs/validate_data_job.rb, app/mailers/application_mailer.rb, app/mailers/notifications_mailer.rb, app/models/application_record.rb, app/models/image.rb, app/models/message.rb, app/models/page.rb, app/models/site.rb, app/models/site_setting.rb, app/models/user.rb, app/uploaders/application_uploader.rb, app/uploaders/image_uploader.rb, app/uploaders/stylesheet_uploader.rb, config/initializers/devise.rb
Change Base classes to Application ready for Rails 5
=> Change Base classes to Application

.rspec, bin/test
Move .rspec config back into bin/test as not needed for guard anymore.
Resolves #650
=> Remove .rspec

doc/google_analytics.md, doc/google_login.md, doc/optional.md
=> Reactor optional docs

app/controllers/application_controller.rb, app/controllers/images_controller.rb, app/controllers/messages_controller.rb, app/controllers/pages_controller.rb, app/controllers/sites_controller.rb, app/controllers/users_controller.rb, app/policies/application_policy.rb, app/policies/page_policy.rb, app/policies/site_policy.rb, app/policies/user_policy.rb
=> Change to use Pundit scopes

spec/features/pages/contact_form_spec.rb, spec/features/pages/delete_spec.rb, spec/features/sites/main_menu_spec.rb, spec/support/features/test_site.rb
=> Refactor test_site

app.json
=> Disable spring on servers

.env.test, app.json, app/views/layouts/_rollbar.html.haml, bin/compile, config/application.rb, config/database.yml, config/initializers/action_mailer.rb, config/initializers/carrierwave.rb, config/puma.rb, config/secrets.yml, db/seeds.rb
=> Change AWS credentials

spec/models/page_spec.rb, spec/models/site_spec.rb, spec/support/features/visit.rb, spec/uploaders/image_uploader_spec.rb, spec/uploaders/stylesheet_uploader_spec.rb
=> Use RSpec contain_exactly

app/controllers/application_controller.rb, spec/features/system/health_spec.rb, spec/features/system/robots_spec.rb, spec/requests/application/unknown_routes_spec.rb, spec/support/features/visit.rb
=> Render 406

app/models/site.rb
Use class instead of string for relation
=> Refactor relation

README.md
=> Added code climate

spec/factories/page_factory.rb, spec/factories/user_factory.rb, spec/features/pages/index_spec.rb, spec/features/pages/show_spec.rb, spec/features/sites/users_spec.rb, spec/jobs/clean_s3_job_spec.rb, spec/jobs/validate_data_job_spec.rb, spec/models/page_spec.rb, spec/requests/pages/show_spec.rb, spec/requests/system/errors_spec.rb, spec/support/features/test_site.rb
=> Use factory traits

spec/active_record/base_spec.rb, spec/support/all/database_cleaner.rb
=> Improve database cleaner

cloudformation/cloudfront.json, cloudformation/iam.json, cloudformation/rds.json, cloudformation/s3.json, cloudformation/sns.json
=> Added AWS CloudFormation

app/controllers/application_controller.rb, spec/requests/application/unknown_routes_spec.rb
=> Fix ActionController::InvalidCrossOriginRequest warnings

app/views/layouts/application.html.haml, app/views/pages/_form.html.haml
=> Fix script errors

app/policies/site_policy.rb, app/policies/system_policy.rb, spec/policies/image_policy_spec.rb, spec/policies/message_policy_spec.rb, spec/policies/page_policy_spec.rb, spec/policies/site_policy_spec.rb, spec/policies/system_policy_spec.rb, spec/policies/user_policy_spec.rb, spec/rails_helper.rb, spec/support/policies.rb
=> Test policies

app.json
=> Upgrade to Heroku 16 stack

Procfile, app.json, spec/support/all/bad_tests.rb
=> Run migrations on deploy

app/jobs/validate_data_job.rb, app/models/application_record.rb, config/initializers/models.rb, config/initializers/will_paginate.rb
=> Load models on boot

app/views/pages/_form.html.haml, config/tinymce.yml, spec/features/pages/create_spec.rb, spec/features/pages/edit_spec.rb
Make them more realistic of real users, and more reliable
=> Refactor JS tests

spec/requests/paper_trail_spec.rb
=> Add request spec for PaperTrail

app/jobs/clean_versions_job.rb, spec/jobs/clean_versions_job_spec.rb
=> Keep old page versions

config/application.rb, spec/requests/api/logging_spec.rb, spec/requests/logging_spec.rb
=> Test logging

app/api/api.rb, app/api/helpers/authentication.rb, app/policies/application_policy.rb, app/policies/page_policy.rb, spec/policies/errors_policy_spec.rb, spec/policies/health_policy_spec.rb, spec/policies/page_policy_spec.rb, spec/requests/api/unknown_routes_spec.rb, spec/support/policies.rb
Make sure site is included in Policies
=> Refactor policies

cloudformation.yaml
=> Add Cloudwatch alarms for failed SNS messages

cloudformation.yaml
Order policy documents the same as AWS documentation does
=> Cloudformation refactor

cloudformation.yaml, config/initializers/carrierwave.rb, spec/uploaders/carrier_wave_spec.rb
=> Encrypt S3 files

app/api/api.rb, app/api/helpers/errors.rb, spec/requests/api/pagination_spec.rb
=> API parameter validation errors

.rubocop.yml, app/api/api.rb, app/api/helpers/errors.rb, app/api/helpers/params.rb, app/api/messages_api.rb, app/controllers/pages_controller.rb, app/mailers/notifications_mailer.rb, app/models/message.rb, app/policies/message_policy.rb, config/locales/api/errors/en.yml, config/locales/api/messages/en.yml, config/locales/api/sns_notifications/en.yml, config/locales/views/mailers/en.yml, db/migrate/20180212145501_remove_message_subject.rb, db/schema.rb, spec/factories/message_factory.rb, spec/features/pages/contact_form_spec.rb, spec/mailers/notifications_mailer_spec.rb, spec/models/message_spec.rb, spec/policies/message_policy_spec.rb, spec/requests/api/authorization_spec.rb, spec/requests/api/errors_spec.rb, spec/requests/api/messages_spec.rb, spec/requests/api/pagination_spec.rb, spec/requests/api/sns_notifications_spec.rb, spec/requests/api/unknown_routes_spec.rb, spec/support/requests/default.rb
=> Add message create API

app/api/api.rb, app/api/entities/system_error.rb, app/api/entities/system_health.rb, app/api/entities/system_message.rb, app/api/health_api.rb, app/api/helpers/errors.rb, app/api/test_errors_api.rb, config/locales/api/errors/en.yml, spec/requests/api/authorization_spec.rb, spec/requests/api/test_errors_spec.rb, spec/requests/api/unknown_routes_spec.rb
=> Consistent API errors

.env.development, .env.test, app/mailers/application_mailer.rb, spec/features/users/edit_spec.rb, spec/features/users/forgot_password_spec.rb, spec/features/users/invite_spec.rb, spec/features/users/locking_spec.rb, spec/mailers/application_mailer_spec.rb, spec/mailers/custom_devise_mailer_spec.rb, spec/support/config/capybara.rb
=> Development email port

app/api/api.rb, app/controllers/application_controller.rb, spec/requests/monitoring_spec.rb, spec/support/shared_contexes/with_request.rb
=> Don't log monitoring requests

app/api/application_api.rb, app/api/messages_api.rb, spec/requests/api/errors_spec.rb, spec/requests/api/pagination_spec.rb
=> Limit API pagination per page

app/webpacker/packs/tinymce.js, app/webpacker/scss/components/_editor.scss, spec/features/pages/create_spec.rb, spec/features/pages/edit_spec.rb
* Make inline so uses same styles as page
* Fix hight so can use toolbar on long pages
=> Fix Tinymce

app/controllers/pages_controller.rb, app/views/pages/_contact_form.html.haml, config/locales/views/pages/en.yml, spec/features/pages/contact_form_spec.rb
* Make privacy policy html5 required
* Add alert error on validation errors
=> Improve form errors

Gemfile, Gemfile.lock, bin/quality
=> Remove bundler audit

app.json
=> Upgrade from Heroku-16 to Heroku-18

Gemfile, Gemfile.lock, app/controllers/pages_controller.rb, app/models/message.rb, app/views/layouts/_main_article.html.erb, app/views/pages/_contact_form.html.erb, app/webpacker/scss/components/_form.scss, config/environments/test.rb, config/locales/models/message/en.yml, spec/features/pages/contact_form_spec.rb, spec/models/message_spec.rb
=> Add invisible_captcha

config/application.rb, spec/requests/logging_spec.rb
=> Log parameters

app.json, cloudformation/app.yaml, config/application.rb, config/environments/production.rb, config/initializers/secure_headers.rb
=> Remove ASSET_HOST

cloudformation/app.yaml, cloudformation/aws-cloudtrail.yaml, cloudformation/aws-config.yaml
=> Force all S3 buckets to be private

config/application.rb, spec/requests/logging_spec.rb
=> Log CloudFlare headers

terraform/app_environment/locals.tf, terraform/app_environment/main.tf, terraform/app_environment/modules/aws_cloudfront/main.tf, terraform/app_environment/modules/aws_cloudfront/outputs.tf, terraform/app_environment/modules/aws_cloudfront/variables.tf, terraform/app_environment/modules/aws_s3/outputs.tf, terraform/app_environment/modules/aws_ses/main.tf, terraform/app_environment/modules/aws_ses/variables.tf, terraform/app_environment/modules/heroku/main.tf, terraform/app_environment/modules/heroku/variables.tf, terraform/app_environment/variables.tf
=> Set up AWS SES with Terraform

app/controllers/sessions_controller.rb, app/mailers/application_mailer.rb, app/mailers/notifications_mailer.rb, app/models/site.rb, app/policies/application_policy.rb, app/policies/site_policy.rb, config/initializers/aws.rb, spec/factories/user_factory.rb, spec/features/login_spec.rb, spec/features/pages/contact_form_spec.rb, spec/features/stylesheet_spec.rb, spec/mailers/notifications_mailer_spec.rb, spec/models/site_spec.rb, spec/policies/page_policy_spec.rb, spec/policies/site_policy_spec.rb, spec/support/shared_contexes/with_test_site.rb, spec/support/shared_examples/policy_for_no_user.rb, spec/support/shared_examples/policy_for_site_admin.rb, spec/support/shared_examples/policy_for_site_user.rb, spec/support/stubs/aws_cognito_list_users_in_group_admin.json, spec/support/stubs/aws_cognito_list_users_in_group_site.json
=> Allow admins to access all sites

terraform/app_environment/modules/heroku/main.tf
=> Remove papertrail heroku addon

terraform/app_environment/.gitignore, terraform/app_environment/main.tf, terraform/app_environment/modules/aws_ses/outputs.tf, terraform/app_environment/modules/cloudflare/locals.tf, terraform/app_environment/modules/cloudflare/main.tf, terraform/app_environment/modules/cloudflare/variables.tf, terraform/app_environment/modules/heroku/outputs.tf, terraform/app_environment/providers.tf, terraform/app_environment/variables.tf, terraform/app_global/.gitignore
=> Set up CloudFlare via Terraform

bin/setup_mac, terraform/app_environment/locals.tf, terraform/app_environment/main.tf, terraform/app_environment/modules/google_monitoring/main.tf, terraform/app_environment/modules/google_monitoring/variables.tf, terraform/app_environment/providers.tf
=> Add Google StackDriver notifications

terraform/app_environment/main.tf, terraform/app_environment/modules/statuscake/main.tf, terraform/app_environment/modules/statuscake/variables.tf, terraform/app_environment/providers.tf
=> Add statuscake monitoring

.rubocop.yml, app/helpers/application_helper.rb, app/jobs/clean_s3_job.rb, bin/spring, config/environments/development.rb, config/initializers/assets.rb, config/initializers/carrierwave.rb, db/migrate/20190624100828_change_from_serial_to_uuid.rb, spec/factories/user_factory.rb, spec/features/admin/sites_spec.rb, spec/features/pages/contact_form_spec.rb, spec/features/sites/footer_links_spec.rb, spec/features/sites/privacy_policy_spec.rb, spec/requests/logging_spec.rb, spec/requests/web_server_spec.rb, spec/support/config/bad_tests.rb, spec/support/config/fog.rb, spec/support/helpers/request_test_helpers.rb, spec/support/shared_contexes/with_test_site.rb, spec/units/active_record/base_spec.rb, spec/uploaders/image_uploader_spec.rb
=> Enable more Rubocop options

terraform/app_environment/main.tf, terraform/app_environment/modules/aws_iam/data.tf, terraform/app_environment/modules/aws_iam/main.tf, terraform/app_environment/modules/aws_iam/outputs.tf, terraform/app_environment/modules/aws_ses/data.tf, terraform/app_environment/modules/aws_ses/main.tf, terraform/app_environment/modules/aws_ses/variables.tf, terraform/app_environment/providers.tf
=> Add ses_identity_policy

terraform/app_environment/main.tf, terraform/app_environment/modules/datadog/main.tf, terraform/app_environment/modules/datadog/variables.tf, terraform/app_environment/providers.tf
=> Add Datadog monitoring

package.json, yarn.lock
This reverts commit 604ce0df283e9833ed9415e61df578ae13ca499e, reversing
changes made to 29d2d6a5598ddc436b9a08a76c3a5931843e9e38.
=> Revert "Merge pull request #4938 from owenbendavies/add-webpack-cli"

.github/workflows/ci.yml
This reverts commit 4f9998c8ff70f28e991fc9c13d78caf03503c6af.
=> Revert "TMP add github debugging"

.github/workflows/automerge.yml
This reverts commit d232a9e6ec490d88faefd0d455d9cbf99ae4b8ce.
=> Revert "TMP add context debug"

.github/workflows/automerge.yml
This reverts commit 6181ecb6016bfe7d46b7a3fb21c264bf7c4b63db.
=> Revert "TMP automerge debug"

.github/workflows/automerge.yml
This reverts commit 97178432b72fa76e8fd9ceb6aaf2af8f9b9493a6.
=> Revert "TMP automerge all to test"
